### ISSUE TITLE
FastBuild For Unreal Engine Error

### ISSUE THREAD

**Issue by ActiveXSturcture** [fastbuild/fastbuild#928]
I try to use FastBuild with Visual Studio 2019 to build Unreal Engine from Source,but after i update the Compiler the error occur:

uilding UnrealEditor and ShaderCompileWorker...
1>Using Visual Studio 2019 14.29.30146 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Determining max actions to execute in parallel (8 physical cores, 8 logical cores)
1>  Executing up to 8 processes, one per physical core
1>Building 82 actions with 8 processes...
1>UnrealBuildTool : error : Unhandled exception: System.ArgumentException: An item with the same key has already been added. Key: UnrealBuildTool.LinkedAction
1>                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
1>                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
1>                           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
1>                           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
1>                           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
1>                           at UnrealBuildTool.ParallelExecutor.ExecuteActions(List`1 InputActions) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Executors\ParallelExecutor.cs:line 183
1>                           at UnrealBuildTool.FASTBuild.ExecuteActions(List`1 Actions) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Executors\Experimental\FASTBuild.cs:line 455
1>                           at UnrealBuildTool.ActionGraph.ExecuteActions(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 370
1>                           at UnrealBuildTool.BuildMode.Build(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 611
1>                           at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, Boolean bSkipPreBuildTargets) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 282
1>                           at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 237
1>                           at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\UnrealEngine\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 612
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: 

I don`t know how this happened and i hope someone who has this problem can help me

**Comment by fsfod** [comment]
That errors not coming from FastBuild but UnrealBuildTool some .ispc compile task gets added more than once because there doesn't seem to be deduplication check when adding child dependencies of prebuild tasks.

**Comment by xiaodaiacg** [comment]
In UnrealBuildTool->FastBuild.cs
function public override bool ExecuteActions(List<LinkedAction> Actions)
`			if (PreCompileActions.Any())
			{
				bool bResult = LocalExecutor.ExecuteActions(PreCompileActions);

				if (!bResult)
					return false;
			}
`
Simply change PreCompileActions to PreCompileActions.Distinct().ToList(),  avoid duplicate compile tasks.

Hope it can help you slove the issue.

**Comment by ActiveXSturcture** [comment]
Thanks xiaodaiacg,after applying you suggest the error not show up,but there are new error occur:

fatal error C1083: Cannot open compiler generated file:"..\Intermediate\Build\Win64\UnrealEditor\Developemnt\MovieSceneTracks\Module.MovieSceneTracks.1_of_3.cpp.json",No such file or directory

**Comment by xiaodaiacg** [comment]
> 

Maybe you should rebuild your engine，I‘ve tested it with UE5.0.0 source and VS2022 17.3.3

**Comment by easthelper** [comment]
It worked for me. with UE5.0.1 
https://github.com/EpicGames/UnrealEngine/commit/4c20b502e6460e263c5cf9360bbea771f9eda1a1

```
			if (PreCompileActions.Any())
			{
				bool bResult = LocalExecutor.ExecuteActions(PreCompileActions, Logger);
				bool bResult = LocalExecutor.ExecuteActions(PreCompileActions.Distinct().ToList(), Logger);

				if (!bResult)
					return false;
```
